[tool.poetry]
name = "alkuaanet"
version = "0.1.0"
description = ""
authors = ["Simo Hellgrén <hellgrensimo@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.25.2"
telepot = "^12.7"
requests = "^2.31.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
black = "^23.7.0"
flake8 = "^6.1.0"
boto3 = "^1.28.66"
uvicorn = "^0.23.2"


[tool.poetry.group.graphql.dependencies]
mangum = "^0.17.0"
strawberry-graphql = {extras = ["asgi"], version = "^0.211"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
