"""song create and update times

Revision ID: 0fff1f89cda3
Revises: 261e1eff7e6c
Create Date: 2021-03-10 19:41:50.820596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0fff1f89cda3"
down_revision = "261e1eff7e6c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "song", sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=True)
    )
    op.add_column(
        "song", sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("song", "updated_at")
    op.drop_column("song", "created_at")
    # ### end Alembic commands ###
