"""initial revision

Revision ID: 261e1eff7e6c
Revises: 
Create Date: 2021-03-08 21:15:48.183920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '261e1eff7e6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('composer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('tones', sa.String(), nullable=True),
    sa.Column('opus', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection_song',
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], )
    )
    op.create_table('composer_song',
    sa.Column('composer_id', sa.Integer(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['composer_id'], ['composer.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('composer_song')
    op.drop_table('collection_song')
    op.drop_table('song')
    op.drop_table('composer')
    op.drop_table('collection')
    # ### end Alembic commands ###
